In [1]:
l = [123, 234, 2345]

In [3]:
l = l + [-345]

In [4]:
l

[123, 234, 2345, -345]

In [5]:
import numpy as np

In [7]:
a=np.array(l)

In [8]:
type(a)

numpy.ndarray

In [9]:
b = np.array([12,34,'a',True,-0.45])

In [10]:
print(b)

['12' '34' 'a' 'True' '-0.45']


In [11]:
#Arrays can only have uniform type unlike list 
 #Hence in array b all the elements were converted into strings

In [12]:
l.pop()

-345

In [13]:
a.mean()

589.25

In [17]:
c = np.array([12,34,-9,True])

In [18]:
print(c)

[12 34 -9  1]


In [19]:
l

[123, 234, 2345]

---

In [20]:
# ----------------------Slicing Array

In [21]:
a

array([ 123,  234, 2345, -345])

In [22]:
a[1:3]

array([ 234, 2345])

In [24]:
b = a[1:3]

In [25]:
b

array([ 234, 2345])

In [26]:
b[:] = 111

In [27]:
b

array([111, 111])

In [28]:
a

array([ 123,  111,  111, -345])

In [29]:
c = a.copy()

In [30]:
c

array([ 123,  111,  111, -345])

In [31]:
c[1] = 0

In [32]:
c

array([ 123,    0,  111, -345])

In [33]:
a

array([ 123,  111,  111, -345])